const CatalogMac = [
    {
        mainImg: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mba15-midnight-select-202306?wid=452&hei=420&fmt=jpeg&qlt=95&.v=1684518479433',
        colorText: 'Midnight',
        colorImg: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mba15-midnight-select-202306_SW_COLOR?wid=32&hei=32&fmt=jpeg&qlt=95&.v=1684183820043',
        chip: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/apple-m2-icon-mac-btr-202306?wid=52&hei=52&fmt=png-alpha&.v=1684190399345',
        chipName: 'm2',
        cpu: '8-Core CPU',
        gpu: '10-Core GPU',
        memoryRam: '8GB Unified Memory',
        memory: '256GB SSD Storage',
        cores: '16-core Neural Engine',
        display: '15.3-inch Liquid Retina display with True Tone',
        camera: '1080p FaceTime HD camera',
        chargPort: 'MagSafe 3 charging port',
        outputs: 'Two Thunderbolt / USB 4 ports',
        accessSecure: 'Magic Keyboard with Touch ID',
        trackPad: 'Force Touch trackpad',
        chAdapter: '35W Dual USB-C Port Compact Power Adapter',
        price: '$1,299.00',
        extraTag: '',
    },
    {
        mainImg: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mba15-starlight-select-202306?wid=452&hei=420&fmt=jpeg&qlt=95&.v=1684518479450',
        colorText: 'Starlight',
        colorImg: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mba15-starlight-select-202306_SW_COLOR?wid=32&hei=32&fmt=jpeg&qlt=95&.v=1684183820158',
        chip: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/apple-m2-icon-mac-btr-202306?wid=52&hei=52&fmt=png-alpha&.v=1684190399345',
        chipName: 'm2',
        cpu: '8-Core CPU',
        gpu: '10-Core GPU',
        memoryRam: '8GB Unified Memory',
        memory: '256GB SSD Storage',
        cores: '16-core Neural Engine',
        display: '15.3-inch Liquid Retina display with True Tone',
        camera: '1080p FaceTime HD camera',
        chargPort: 'MagSafe 3 charging port',
        outputs: 'Two Thunderbolt / USB 4 ports',
        accessSecure: 'Magic Keyboard with Touch ID',
        trackPad: 'Force Touch trackpad',
        chAdapter: '35W Dual USB-C Port Compact Power Adapter',
        price: '$1,299.00',
        extraTag: '',
    },
    {
        mainImg: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mba15-spacegray-select-202306?wid=452&hei=420&fmt=jpeg&qlt=95&.v=1684518479428',
        colorText: 'Space Gray',
        colorImg: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mba15-spacegray-select-202306_SW_COLOR?wid=32&hei=32&fmt=jpeg&qlt=95&.v=1684183820160',
        chip: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/apple-m2-icon-mac-btr-202306?wid=52&hei=52&fmt=png-alpha&.v=1684190399345',
        chipName: 'm2',
        cpu: '8-Core CPU',
        gpu: '10-Core GPU',
        memoryRam: '8GB Unified Memory',
        memory: '256GB SSD Storage',
        cores: '16-core Neural Engine',
        display: '15.3-inch Liquid Retina display with True Tone',
        camera: '1080p FaceTime HD camera',
        chargPort: 'MagSafe 3 charging port',
        outputs: 'Two Thunderbolt / USB 4 ports',
        accessSecure: 'Magic Keyboard with Touch ID',
        trackPad: 'Force Touch trackpad',
        chAdapter: '35W Dual USB-C Port Compact Power Adapter',
        price: '$1,299.00',
        extraTag: '',
    },
    {
        mainImg: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mba15-silver-select-202306?wid=452&hei=420&fmt=jpeg&qlt=95&.v=1684518479266',
        colorText: 'Silver',
        colorImg: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mba15-silver-select-202306_SW_COLOR?wid=32&hei=32&fmt=jpeg&qlt=95&.v=1684183820142',
        chip: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/apple-m2-icon-mac-btr-202306?wid=52&hei=52&fmt=png-alpha&.v=1684190399345',
        chipName: 'm2',
        cpu: '8-Core CPU',
        gpu: '10-Core GPU',
        memoryRam: '8GB Unified Memory',
        memory: '256GB SSD Storage',
        cores: '16-core Neural Engine',
        display: '15.3-inch Liquid Retina display with True Tone',
        camera: '1080p FaceTime HD camera',
        chargPort: 'MagSafe 3 charging port',
        outputs: 'Two Thunderbolt / USB 4 ports',
        accessSecure: 'Magic Keyboard with Touch ID',
        trackPad: 'Force Touch trackpad',
        chAdapter: '35W Dual USB-C Port Compact Power Adapter',
        price: '$1,299.00',
        extraTag: '',
    },
    {
        mainImg: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mba15-midnight-select-202306?wid=452&hei=420&fmt=jpeg&qlt=95&.v=1684518479433',
        colorText: 'Midnight',
        colorImg: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mba15-midnight-select-202306_SW_COLOR?wid=32&hei=32&fmt=jpeg&qlt=95&.v=1684183820043',
        chip: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/apple-m2-icon-mac-btr-202306?wid=52&hei=52&fmt=png-alpha&.v=1684190399345',
        chipName: 'm2',
        cpu: '8-Core CPU',
        gpu: '10-Core GPU',
        memoryRam: '8GB Unified Memory',
        memory: '512GB SSD Storage',
        cores: '16-core Neural Engine',
        display: '15.3-inch Liquid Retina display with True Tone',
        camera: '1080p FaceTime HD camera',
        chargPort: 'MagSafe 3 charging port',
        outputs: 'Two Thunderbolt / USB 4 ports',
        accessSecure: 'Magic Keyboard with Touch ID',
        trackPad: 'Force Touch trackpad',
        chAdapter: '35W Dual USB-C Port Compact Power Adapter',
        price: '$1,499.00',
        extraTag: '',
    },
    {
        mainImg: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mba15-starlight-select-202306?wid=452&hei=420&fmt=jpeg&qlt=95&.v=1684518479450',
        colorText: 'Starlight',
        colorImg: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mba15-starlight-select-202306_SW_COLOR?wid=32&hei=32&fmt=jpeg&qlt=95&.v=1684183820158',
        chip: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/apple-m2-icon-mac-btr-202306?wid=52&hei=52&fmt=png-alpha&.v=1684190399345',
        chipName: 'm2',
        cpu: '8-Core CPU',
        gpu: '10-Core GPU',
        memoryRam: '8GB Unified Memory',
        memory: '512GB SSD Storage',
        cores: '16-core Neural Engine',
        display: '15.3-inch Liquid Retina display with True Tone',
        camera: '1080p FaceTime HD camera',
        chargPort: 'MagSafe 3 charging port',
        outputs: 'Two Thunderbolt / USB 4 ports',
        accessSecure: 'Magic Keyboard with Touch ID',
        trackPad: 'Force Touch trackpad',
        chAdapter: '35W Dual USB-C Port Compact Power Adapter',
        price: '$1,499.00',
        extraTag: '',
    },
    {
        mainImg: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mba15-spacegray-select-202306?wid=452&hei=420&fmt=jpeg&qlt=95&.v=1684518479428',
        colorText: 'Space Gray',
        colorImg: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mba15-spacegray-select-202306_SW_COLOR?wid=32&hei=32&fmt=jpeg&qlt=95&.v=1684183820160',
        chip: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/apple-m2-icon-mac-btr-202306?wid=52&hei=52&fmt=png-alpha&.v=1684190399345',
        chipName: 'm2',
        cpu: '8-Core CPU',
        gpu: '10-Core GPU',
        memoryRam: '8GB Unified Memory',
        memory: '512GB SSD Storage',
        cores: '16-core Neural Engine',
        display: '15.3-inch Liquid Retina display with True Tone',
        camera: '1080p FaceTime HD camera',
        chargPort: 'MagSafe 3 charging port',
        outputs: 'Two Thunderbolt / USB 4 ports',
        accessSecure: 'Magic Keyboard with Touch ID',
        trackPad: 'Force Touch trackpad',
        chAdapter: '35W Dual USB-C Port Compact Power Adapter',
        price: '$1,499.00',
        extraTag: '',
    },
    {
        mainImg: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mba15-silver-select-202306?wid=452&hei=420&fmt=jpeg&qlt=95&.v=1684518479266',
        colorText: 'Silver',
        colorImg: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mba15-silver-select-202306_SW_COLOR?wid=32&hei=32&fmt=jpeg&qlt=95&.v=1684183820142',
        chip: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/apple-m2-icon-mac-btr-202306?wid=52&hei=52&fmt=png-alpha&.v=1684190399345',
        chipName: 'm2',
        cpu: '8-Core CPU',
        gpu: '10-Core GPU',
        memoryRam: '8GB Unified Memory',
        memory: '512GB SSD Storage',
        cores: '16-core Neural Engine',
        display: '15.3-inch Liquid Retina display with True Tone',
        camera: '1080p FaceTime HD camera',
        chargPort: 'MagSafe 3 charging port',
        outputs: 'Two Thunderbolt / USB 4 ports',
        accessSecure: 'Magic Keyboard with Touch ID',
        trackPad: 'Force Touch trackpad',
        chAdapter: '35W Dual USB-C Port Compact Power Adapter',
        price: '$1,499.00',
        extraTag: '',
    },
    {
        mainImg: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/macbook-air-midnight-select-20220606?wid=452&hei=420&fmt=jpeg&qlt=95&.v=1653084303665',
        colorText: 'Midnight',
        colorImg: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/macbook-air-midnight-select-20220606_SW_COLOR?wid=32&hei=32&fmt=jpeg&qlt=95&.v=1654147903807',
        chip: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/apple-m2-icon-mac-btr-202306?wid=52&hei=52&fmt=png-alpha&.v=1684190399345',
        chipName: 'm2',
        cpu: '8-Core CPU',
        gpu: '8-Core GPU',
        memoryRam: '8GB Unified Memory',
        memory: '256GB SSD Storagefootnote',
        cores: '16-core Neural Engine',
        display: '13.6-inch Liquid Retina display with True Tone',
        camera: '1080p FaceTime HD camera',
        chargPort: 'MagSafe 3 charging port',
        outputs: 'Two Thunderbolt / USB 4 ports',
        accessSecure: 'Magic Keyboard with Touch ID',
        trackPad: 'Force Touch trackpad',
        chAdapter: '30W USB-C Power Adapter',
        price: '$1,099.00',
        extraTag: '',
    },
    {
        mainImg: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/macbook-air-starlight-select-20220606?wid=452&hei=420&fmt=jpeg&qlt=95&.v=1653084303732',
        colorText: 'Starlight',
        colorImg: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/macbook-air-starlight-select-20220606_SW_COLOR?wid=32&hei=32&fmt=jpeg&qlt=95&.v=1654147903808',
        chip: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/apple-m2-icon-mac-btr-202306?wid=52&hei=52&fmt=png-alpha&.v=1684190399345',
        chipName: 'm2',
        cpu: '8-Core CPU',
        gpu: '8-Core GPU',
        memoryRam: '8GB Unified Memory',
        memory: '256GB SSD Storagefootnote',
        cores: '16-core Neural Engine',
        display: '13.6-inch Liquid Retina display with True Tone',
        camera: '1080p FaceTime HD camera',
        chargPort: 'MagSafe 3 charging port',
        outputs: 'Two Thunderbolt / USB 4 ports',
        accessSecure: 'Magic Keyboard with Touch ID',
        trackPad: 'Force Touch trackpad',
        chAdapter: '30W USB-C Power Adapter',
        price: '$1,099.00',
        extraTag: '',
    },
    {
        mainImg: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/macbook-air-spacegray-select-20220606?wid=452&hei=420&fmt=jpeg&qlt=95&.v=1653084303733',
        colorText: 'Space Gray',
        colorImg: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/macbook-air-spacegray-select-20220606_SW_COLOR?wid=32&hei=32&fmt=jpeg&qlt=95&.v=1654147903803',
        chip: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/apple-m2-icon-mac-btr-202306?wid=52&hei=52&fmt=png-alpha&.v=1684190399345',
        chipName: 'm2',
        cpu: '8-Core CPU',
        gpu: '8-Core GPU',
        memoryRam: '8GB Unified Memory',
        memory: '256GB SSD Storagefootnote',
        cores: '16-core Neural Engine',
        display: '13.6-inch Liquid Retina display with True Tone',
        camera: '1080p FaceTime HD camera',
        chargPort: 'MagSafe 3 charging port',
        outputs: 'Two Thunderbolt / USB 4 ports',
        accessSecure: 'Magic Keyboard with Touch ID',
        trackPad: 'Force Touch trackpad',
        chAdapter: '30W USB-C Power Adapter',
        price: '$1,099.00',
        extraTag: '',
    },
    {
        mainImg: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/macbook-air-silver-select-20220606?wid=452&hei=420&fmt=jpeg&qlt=95&.v=1653084303678',
        colorText: 'Silver',
        colorImg: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/macbook-air-silver-select-20220606_SW_COLOR?wid=32&hei=32&fmt=jpeg&qlt=95&.v=1654147903807',
        chip: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/apple-m2-icon-mac-btr-202306?wid=52&hei=52&fmt=png-alpha&.v=1684190399345',
        chipName: 'm2',
        cpu: '8-Core CPU',
        gpu: '8-Core GPU',
        memoryRam: '8GB Unified Memory',
        memory: '256GB SSD Storagefootnote',
        cores: '16-core Neural Engine',
        display: '13.6-inch Liquid Retina display with True Tone',
        camera: '1080p FaceTime HD camera',
        chargPort: 'MagSafe 3 charging port',
        outputs: 'Two Thunderbolt / USB 4 ports',
        accessSecure: 'Magic Keyboard with Touch ID',
        trackPad: 'Force Touch trackpad',
        chAdapter: '30W USB-C Power Adapter',
        price: '$1,099.00',
        extraTag: '',
    },
    {
        mainImg: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/macbook-air-midnight-select-20220606?wid=452&hei=420&fmt=jpeg&qlt=95&.v=1653084303665',
        colorText: 'Midnight',
        colorImg: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/macbook-air-midnight-select-20220606_SW_COLOR?wid=32&hei=32&fmt=jpeg&qlt=95&.v=1654147903807',
        chip: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/apple-m2-icon-mac-btr-202306?wid=52&hei=52&fmt=png-alpha&.v=1684190399345',
        chipName: 'm2',
        cpu: '8-Core CPU',
        gpu: '10-Core GPU',
        memoryRam: '8GB Unified Memory',
        memory: '512GB SSD Storagefootnote',
        cores: '16-core Neural Engine',
        display: '13.6-inch Liquid Retina display with True Tone',
        camera: '1080p FaceTime HD camera',
        chargPort: 'MagSafe 3 charging port',
        outputs: 'Two Thunderbolt / USB 4 ports',
        accessSecure: 'Magic Keyboard with Touch ID',
        trackPad: 'Force Touch trackpad',
        chAdapter: '35W Dual USB-C Port Compact Power Adapter',
        price: '$1,399.00',
        extraTag: '',
    },
    {
        mainImg: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/macbook-air-starlight-select-20220606?wid=452&hei=420&fmt=jpeg&qlt=95&.v=1653084303732',
        colorText: 'Starlight',
        colorImg: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/macbook-air-starlight-select-20220606_SW_COLOR?wid=32&hei=32&fmt=jpeg&qlt=95&.v=1654147903808',
        chip: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/apple-m2-icon-mac-btr-202306?wid=52&hei=52&fmt=png-alpha&.v=1684190399345',
        chipName: 'm2',
        cpu: '8-Core CPU',
        gpu: '10-Core GPU',
        memoryRam: '8GB Unified Memory',
        memory: '512GB SSD Storagefootnote',
        cores: '16-core Neural Engine',
        display: '13.6-inch Liquid Retina display with True Tone',
        camera: '1080p FaceTime HD camera',
        chargPort: 'MagSafe 3 charging port',
        outputs: 'Two Thunderbolt / USB 4 ports',
        accessSecure: 'Magic Keyboard with Touch ID',
        trackPad: 'Force Touch trackpad',
        chAdapter: '35W Dual USB-C Port Compact Power Adapter',
        price: '$1,399.00',
        extraTag: '',
    },{
        mainImg: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/macbook-air-spacegray-select-20220606?wid=452&hei=420&fmt=jpeg&qlt=95&.v=1653084303733',
        colorText: 'Space Gray',
        colorImg: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/macbook-air-spacegray-select-20220606_SW_COLOR?wid=32&hei=32&fmt=jpeg&qlt=95&.v=1654147903803',
        chip: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/apple-m2-icon-mac-btr-202306?wid=52&hei=52&fmt=png-alpha&.v=1684190399345',
        chipName: 'm2',
        cpu: '8-Core CPU',
        gpu: '10-Core GPU',
        memoryRam: '8GB Unified Memory',
        memory: '512GB SSD Storagefootnote',
        cores: '16-core Neural Engine',
        display: '13.6-inch Liquid Retina display with True Tone',
        camera: '1080p FaceTime HD camera',
        chargPort: 'MagSafe 3 charging port',
        outputs: 'Two Thunderbolt / USB 4 ports',
        accessSecure: 'Magic Keyboard with Touch ID',
        trackPad: 'Force Touch trackpad',
        chAdapter: '35W Dual USB-C Port Compact Power Adapter',
        price: '$1,399.00',
        extraTag: '',
    },{
        mainImg: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/macbook-air-silver-select-20220606?wid=452&hei=420&fmt=jpeg&qlt=95&.v=1653084303678',
        colorText: 'Silver',
        colorImg: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/macbook-air-silver-select-20220606_SW_COLOR?wid=32&hei=32&fmt=jpeg&qlt=95&.v=1654147903807',
        chip: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/apple-m2-icon-mac-btr-202306?wid=52&hei=52&fmt=png-alpha&.v=1684190399345',
        chipName: 'm2',
        cpu: '8-Core CPU',
        gpu: '10-Core GPU',
        memoryRam: '8GB Unified Memory',
        memory: '512GB SSD Storagefootnote',
        cores: '16-core Neural Engine',
        display: '13.6-inch Liquid Retina display with True Tone',
        camera: '1080p FaceTime HD camera',
        chargPort: 'MagSafe 3 charging port',
        outputs: 'Two Thunderbolt / USB 4 ports',
        accessSecure: 'Magic Keyboard with Touch ID',
        trackPad: 'Force Touch trackpad',
        chAdapter: '35W Dual USB-C Port Compact Power Adapter',
        price: '$1,399.00',
        extraTag: '',
    },
    {
        mainImg: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/macbook-air-space-gray-select-201810?wid=452&hei=420&fmt=jpeg&qlt=95&.v=1664472289661',
        colorText: 'Space Gray',
        colorImg: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/macbook-air-space-gray-select-201810_SW_COLOR?wid=32&hei=32&fmt=jpeg&qlt=95&.v=1654147903806',
        chip: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/apple-m1-icon-mac-btr-202306?wid=52&hei=52&fmt=png-alpha&.v=1686159230838',
        chipName: 'm1',
        cpu: '8-Core CPU',
        gpu: '7-Core GPU',
        memoryRam: '8GB Unified Memory',
        memory: '256GB SSD Storage',
        cores: '16-core Neural Engine',
        display: '13-inch Retina display with True Tone',
        camera: '-',
        chargPort: '-',
        outputs: 'Two Thunderbolt / USB 4 ports',
        accessSecure: 'Magic Keyboard with Touch ID',
        trackPad: 'Force Touch trackpad',
        chAdapter: '30W USB-C Power Adapter',
        price: '$999.00',
        extraTag: '',
    },
    {
        mainImg: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/macbook-air-gold-select-201810?wid=452&hei=420&fmt=jpeg&qlt=95&.v=1664472289059',
        colorText: 'Gold',
        colorImg: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/macbook-air-gold-select-201810_SW_COLOR?wid=32&hei=32&fmt=jpeg&qlt=95&.v=1654147903806',
        chip: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/apple-m1-icon-mac-btr-202306?wid=52&hei=52&fmt=png-alpha&.v=1686159230838',
        chipName: 'm1',
        cpu: '8-Core CPU',
        gpu: '7-Core GPU',
        memoryRam: '8GB Unified Memory',
        memory: '256GB SSD Storage',
        cores: '16-core Neural Engine',
        display: '13-inch Retina display with True Tone',
        camera: '-',
        chargPort: '-',
        outputs: 'Two Thunderbolt / USB 4 ports',
        accessSecure: 'Magic Keyboard with Touch ID',
        trackPad: 'Force Touch trackpad',
        chAdapter: '30W USB-C Power Adapter',
        price: '$999.00',
        extraTag: '',
    },
    {
        mainImg: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/macbook-air-silver-select-201810?wid=452&hei=420&fmt=jpeg&qlt=95&.v=1664472289056',
        colorText: 'Silver',
        colorImg: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/macbook-air-silver-select-201810_SW_COLOR?wid=32&hei=32&fmt=jpeg&qlt=95&.v=1654147903776',
        chip: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/apple-m1-icon-mac-btr-202306?wid=52&hei=52&fmt=png-alpha&.v=1686159230838',
        chipName: 'm1',
        cpu: '8-Core CPU',
        gpu: '7-Core GPU',
        memoryRam: '8GB Unified Memory',
        memory: '256GB SSD Storage',
        cores: '16-core Neural Engine',
        display: '13-inch Retina display with True Tone',
        camera: '-',
        chargPort: '-',
        outputs: 'Two Thunderbolt / USB 4 ports',
        accessSecure: 'Magic Keyboard with Touch ID',
        trackPad: 'Force Touch trackpad',
        chAdapter: '30W USB-C Power Adapter',
        price: '$999.00',
        extraTag: '',
    },
    // {
    //     mainImg: '',
    //     colorText: '',
    //     colorImg: '',
    //     chip: '',
    //     cpu: '',
    //     gpu: '',
    //     memoryRam: '',
    //     memory: '',
    //     cores: '',
    //     display: '',
    //     camera: '',
    //     chargPort: '',
    //     outputs: '',
    //     accessSecure: '',
    //     trackPad: '',
    //     chAdapter: '',
    //     price: '',
    //     extraTag: '',
    // },
]

export default CatalogMac;